/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjCnae;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjCnaeSecundario;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjEndereco;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjMotivoSituacaoCadastral;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjNaturezaJuridica;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjOpcaoSimei;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjOpcaoSimples;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjPais;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjPorteEmpresa;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjSituacaoCadastral;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjSituacaoEspecial;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjSocio;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CnpjTelefone;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.com.caonulisses.nuvemfiscalsdk.JSON;

/**
 * CnpjEmpresa
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class CnpjEmpresa {
  public static final String SERIALIZED_NAME_CNPJ = "cnpj";
  @SerializedName(SERIALIZED_NAME_CNPJ)
  @javax.annotation.Nullable
  private String cnpj;

  public static final String SERIALIZED_NAME_RAZAO_SOCIAL = "razao_social";
  @SerializedName(SERIALIZED_NAME_RAZAO_SOCIAL)
  @javax.annotation.Nullable
  private String razaoSocial;

  public static final String SERIALIZED_NAME_NOME_FANTASIA = "nome_fantasia";
  @SerializedName(SERIALIZED_NAME_NOME_FANTASIA)
  @javax.annotation.Nullable
  private String nomeFantasia;

  public static final String SERIALIZED_NAME_DATA_INICIO_ATIVIDADE = "data_inicio_atividade";
  @SerializedName(SERIALIZED_NAME_DATA_INICIO_ATIVIDADE)
  @javax.annotation.Nullable
  private LocalDate dataInicioAtividade;

  public static final String SERIALIZED_NAME_MATRIZ = "matriz";
  @SerializedName(SERIALIZED_NAME_MATRIZ)
  @javax.annotation.Nullable
  private Boolean matriz;

  public static final String SERIALIZED_NAME_NATUREZA_JURIDICA = "natureza_juridica";
  @SerializedName(SERIALIZED_NAME_NATUREZA_JURIDICA)
  @javax.annotation.Nullable
  private CnpjNaturezaJuridica naturezaJuridica;

  public static final String SERIALIZED_NAME_CAPITAL_SOCIAL = "capital_social";
  @SerializedName(SERIALIZED_NAME_CAPITAL_SOCIAL)
  @javax.annotation.Nullable
  private BigDecimal capitalSocial;

  public static final String SERIALIZED_NAME_PORTE = "porte";
  @SerializedName(SERIALIZED_NAME_PORTE)
  @javax.annotation.Nullable
  private CnpjPorteEmpresa porte;

  public static final String SERIALIZED_NAME_ENTE_FEDERATIVO_RESPONSAVEL = "ente_federativo_responsavel";
  @SerializedName(SERIALIZED_NAME_ENTE_FEDERATIVO_RESPONSAVEL)
  @javax.annotation.Nullable
  private String enteFederativoResponsavel;

  public static final String SERIALIZED_NAME_SITUACAO_CADASTRAL = "situacao_cadastral";
  @SerializedName(SERIALIZED_NAME_SITUACAO_CADASTRAL)
  @javax.annotation.Nullable
  private CnpjSituacaoCadastral situacaoCadastral;

  public static final String SERIALIZED_NAME_MOTIVO_SITUACAO_CADASTRAL = "motivo_situacao_cadastral";
  @SerializedName(SERIALIZED_NAME_MOTIVO_SITUACAO_CADASTRAL)
  @javax.annotation.Nullable
  private CnpjMotivoSituacaoCadastral motivoSituacaoCadastral;

  public static final String SERIALIZED_NAME_NOME_DA_CIDADE_NO_EXTERIOR = "nome_da_cidade_no_exterior";
  @SerializedName(SERIALIZED_NAME_NOME_DA_CIDADE_NO_EXTERIOR)
  @javax.annotation.Nullable
  private String nomeDaCidadeNoExterior;

  public static final String SERIALIZED_NAME_PAIS = "pais";
  @SerializedName(SERIALIZED_NAME_PAIS)
  @javax.annotation.Nullable
  private CnpjPais pais;

  public static final String SERIALIZED_NAME_ATIVIDADE_PRINCIPAL = "atividade_principal";
  @SerializedName(SERIALIZED_NAME_ATIVIDADE_PRINCIPAL)
  @javax.annotation.Nullable
  private CnpjCnae atividadePrincipal;

  public static final String SERIALIZED_NAME_ATIVIDADES_SECUNDARIAS = "atividades_secundarias";
  @SerializedName(SERIALIZED_NAME_ATIVIDADES_SECUNDARIAS)
  @javax.annotation.Nullable
  private List<CnpjCnaeSecundario> atividadesSecundarias = new ArrayList<>();

  public static final String SERIALIZED_NAME_ENDERECO = "endereco";
  @SerializedName(SERIALIZED_NAME_ENDERECO)
  @javax.annotation.Nullable
  private CnpjEndereco endereco;

  public static final String SERIALIZED_NAME_TELEFONES = "telefones";
  @SerializedName(SERIALIZED_NAME_TELEFONES)
  @javax.annotation.Nullable
  private List<CnpjTelefone> telefones = new ArrayList<>();

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_SITUACAO_ESPECIAL = "situacao_especial";
  @SerializedName(SERIALIZED_NAME_SITUACAO_ESPECIAL)
  @javax.annotation.Nullable
  private CnpjSituacaoEspecial situacaoEspecial;

  public static final String SERIALIZED_NAME_SIMPLES = "simples";
  @SerializedName(SERIALIZED_NAME_SIMPLES)
  @javax.annotation.Nullable
  private CnpjOpcaoSimples simples;

  public static final String SERIALIZED_NAME_SIMEI = "simei";
  @SerializedName(SERIALIZED_NAME_SIMEI)
  @javax.annotation.Nullable
  private CnpjOpcaoSimei simei;

  public static final String SERIALIZED_NAME_SOCIOS = "socios";
  @SerializedName(SERIALIZED_NAME_SOCIOS)
  @javax.annotation.Nullable
  private List<CnpjSocio> socios = new ArrayList<>();

  public CnpjEmpresa() {
  }

  public CnpjEmpresa cnpj(@javax.annotation.Nullable String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

  /**
   * Número de inscrição do CNPJ.
   * @return cnpj
   */
  @javax.annotation.Nullable
  public String getCnpj() {
    return cnpj;
  }

  public void setCnpj(@javax.annotation.Nullable String cnpj) {
    this.cnpj = cnpj;
  }


  public CnpjEmpresa razaoSocial(@javax.annotation.Nullable String razaoSocial) {
    this.razaoSocial = razaoSocial;
    return this;
  }

  /**
   * Nome empresarial da pessoa jurídica.
   * @return razaoSocial
   */
  @javax.annotation.Nullable
  public String getRazaoSocial() {
    return razaoSocial;
  }

  public void setRazaoSocial(@javax.annotation.Nullable String razaoSocial) {
    this.razaoSocial = razaoSocial;
  }


  public CnpjEmpresa nomeFantasia(@javax.annotation.Nullable String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
    return this;
  }

  /**
   * Corresponde ao nome fantasia.
   * @return nomeFantasia
   */
  @javax.annotation.Nullable
  public String getNomeFantasia() {
    return nomeFantasia;
  }

  public void setNomeFantasia(@javax.annotation.Nullable String nomeFantasia) {
    this.nomeFantasia = nomeFantasia;
  }


  public CnpjEmpresa dataInicioAtividade(@javax.annotation.Nullable LocalDate dataInicioAtividade) {
    this.dataInicioAtividade = dataInicioAtividade;
    return this;
  }

  /**
   * Data de início da atividade.
   * @return dataInicioAtividade
   */
  @javax.annotation.Nullable
  public LocalDate getDataInicioAtividade() {
    return dataInicioAtividade;
  }

  public void setDataInicioAtividade(@javax.annotation.Nullable LocalDate dataInicioAtividade) {
    this.dataInicioAtividade = dataInicioAtividade;
  }


  public CnpjEmpresa matriz(@javax.annotation.Nullable Boolean matriz) {
    this.matriz = matriz;
    return this;
  }

  /**
   * Indicador de matriz/filial:  * &#x60;true&#x60; - É matriz  * &#x60;false&#x60; - É filial
   * @return matriz
   */
  @javax.annotation.Nullable
  public Boolean getMatriz() {
    return matriz;
  }

  public void setMatriz(@javax.annotation.Nullable Boolean matriz) {
    this.matriz = matriz;
  }


  public CnpjEmpresa naturezaJuridica(@javax.annotation.Nullable CnpjNaturezaJuridica naturezaJuridica) {
    this.naturezaJuridica = naturezaJuridica;
    return this;
  }

  /**
   * Get naturezaJuridica
   * @return naturezaJuridica
   */
  @javax.annotation.Nullable
  public CnpjNaturezaJuridica getNaturezaJuridica() {
    return naturezaJuridica;
  }

  public void setNaturezaJuridica(@javax.annotation.Nullable CnpjNaturezaJuridica naturezaJuridica) {
    this.naturezaJuridica = naturezaJuridica;
  }


  public CnpjEmpresa capitalSocial(@javax.annotation.Nullable BigDecimal capitalSocial) {
    this.capitalSocial = capitalSocial;
    return this;
  }

  /**
   * Capital social da empresa.
   * @return capitalSocial
   */
  @javax.annotation.Nullable
  public BigDecimal getCapitalSocial() {
    return capitalSocial;
  }

  public void setCapitalSocial(@javax.annotation.Nullable BigDecimal capitalSocial) {
    this.capitalSocial = capitalSocial;
  }


  public CnpjEmpresa porte(@javax.annotation.Nullable CnpjPorteEmpresa porte) {
    this.porte = porte;
    return this;
  }

  /**
   * Get porte
   * @return porte
   */
  @javax.annotation.Nullable
  public CnpjPorteEmpresa getPorte() {
    return porte;
  }

  public void setPorte(@javax.annotation.Nullable CnpjPorteEmpresa porte) {
    this.porte = porte;
  }


  public CnpjEmpresa enteFederativoResponsavel(@javax.annotation.Nullable String enteFederativoResponsavel) {
    this.enteFederativoResponsavel = enteFederativoResponsavel;
    return this;
  }

  /**
   * O ente federativo responsável é preenchido para os casos de órgãos e  entidades do grupo de natureza jurídica 1XXX. Para as demais naturezas,  este atributo fica em branco.
   * @return enteFederativoResponsavel
   */
  @javax.annotation.Nullable
  public String getEnteFederativoResponsavel() {
    return enteFederativoResponsavel;
  }

  public void setEnteFederativoResponsavel(@javax.annotation.Nullable String enteFederativoResponsavel) {
    this.enteFederativoResponsavel = enteFederativoResponsavel;
  }


  public CnpjEmpresa situacaoCadastral(@javax.annotation.Nullable CnpjSituacaoCadastral situacaoCadastral) {
    this.situacaoCadastral = situacaoCadastral;
    return this;
  }

  /**
   * Get situacaoCadastral
   * @return situacaoCadastral
   */
  @javax.annotation.Nullable
  public CnpjSituacaoCadastral getSituacaoCadastral() {
    return situacaoCadastral;
  }

  public void setSituacaoCadastral(@javax.annotation.Nullable CnpjSituacaoCadastral situacaoCadastral) {
    this.situacaoCadastral = situacaoCadastral;
  }


  public CnpjEmpresa motivoSituacaoCadastral(@javax.annotation.Nullable CnpjMotivoSituacaoCadastral motivoSituacaoCadastral) {
    this.motivoSituacaoCadastral = motivoSituacaoCadastral;
    return this;
  }

  /**
   * Get motivoSituacaoCadastral
   * @return motivoSituacaoCadastral
   */
  @javax.annotation.Nullable
  public CnpjMotivoSituacaoCadastral getMotivoSituacaoCadastral() {
    return motivoSituacaoCadastral;
  }

  public void setMotivoSituacaoCadastral(@javax.annotation.Nullable CnpjMotivoSituacaoCadastral motivoSituacaoCadastral) {
    this.motivoSituacaoCadastral = motivoSituacaoCadastral;
  }


  public CnpjEmpresa nomeDaCidadeNoExterior(@javax.annotation.Nullable String nomeDaCidadeNoExterior) {
    this.nomeDaCidadeNoExterior = nomeDaCidadeNoExterior;
    return this;
  }

  /**
   * Nome da cidade no exterior.
   * @return nomeDaCidadeNoExterior
   */
  @javax.annotation.Nullable
  public String getNomeDaCidadeNoExterior() {
    return nomeDaCidadeNoExterior;
  }

  public void setNomeDaCidadeNoExterior(@javax.annotation.Nullable String nomeDaCidadeNoExterior) {
    this.nomeDaCidadeNoExterior = nomeDaCidadeNoExterior;
  }


  public CnpjEmpresa pais(@javax.annotation.Nullable CnpjPais pais) {
    this.pais = pais;
    return this;
  }

  /**
   * Get pais
   * @return pais
   */
  @javax.annotation.Nullable
  public CnpjPais getPais() {
    return pais;
  }

  public void setPais(@javax.annotation.Nullable CnpjPais pais) {
    this.pais = pais;
  }


  public CnpjEmpresa atividadePrincipal(@javax.annotation.Nullable CnpjCnae atividadePrincipal) {
    this.atividadePrincipal = atividadePrincipal;
    return this;
  }

  /**
   * Get atividadePrincipal
   * @return atividadePrincipal
   */
  @javax.annotation.Nullable
  public CnpjCnae getAtividadePrincipal() {
    return atividadePrincipal;
  }

  public void setAtividadePrincipal(@javax.annotation.Nullable CnpjCnae atividadePrincipal) {
    this.atividadePrincipal = atividadePrincipal;
  }


  public CnpjEmpresa atividadesSecundarias(@javax.annotation.Nullable List<CnpjCnaeSecundario> atividadesSecundarias) {
    this.atividadesSecundarias = atividadesSecundarias;
    return this;
  }

  public CnpjEmpresa addAtividadesSecundariasItem(CnpjCnaeSecundario atividadesSecundariasItem) {
    if (this.atividadesSecundarias == null) {
      this.atividadesSecundarias = new ArrayList<>();
    }
    this.atividadesSecundarias.add(atividadesSecundariasItem);
    return this;
  }

  /**
   * Get atividadesSecundarias
   * @return atividadesSecundarias
   */
  @javax.annotation.Nullable
  public List<CnpjCnaeSecundario> getAtividadesSecundarias() {
    return atividadesSecundarias;
  }

  public void setAtividadesSecundarias(@javax.annotation.Nullable List<CnpjCnaeSecundario> atividadesSecundarias) {
    this.atividadesSecundarias = atividadesSecundarias;
  }


  public CnpjEmpresa endereco(@javax.annotation.Nullable CnpjEndereco endereco) {
    this.endereco = endereco;
    return this;
  }

  /**
   * Get endereco
   * @return endereco
   */
  @javax.annotation.Nullable
  public CnpjEndereco getEndereco() {
    return endereco;
  }

  public void setEndereco(@javax.annotation.Nullable CnpjEndereco endereco) {
    this.endereco = endereco;
  }


  public CnpjEmpresa telefones(@javax.annotation.Nullable List<CnpjTelefone> telefones) {
    this.telefones = telefones;
    return this;
  }

  public CnpjEmpresa addTelefonesItem(CnpjTelefone telefonesItem) {
    if (this.telefones == null) {
      this.telefones = new ArrayList<>();
    }
    this.telefones.add(telefonesItem);
    return this;
  }

  /**
   * Get telefones
   * @return telefones
   */
  @javax.annotation.Nullable
  public List<CnpjTelefone> getTelefones() {
    return telefones;
  }

  public void setTelefones(@javax.annotation.Nullable List<CnpjTelefone> telefones) {
    this.telefones = telefones;
  }


  public CnpjEmpresa email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * E-mail do contribuinte.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public CnpjEmpresa situacaoEspecial(@javax.annotation.Nullable CnpjSituacaoEspecial situacaoEspecial) {
    this.situacaoEspecial = situacaoEspecial;
    return this;
  }

  /**
   * Get situacaoEspecial
   * @return situacaoEspecial
   */
  @javax.annotation.Nullable
  public CnpjSituacaoEspecial getSituacaoEspecial() {
    return situacaoEspecial;
  }

  public void setSituacaoEspecial(@javax.annotation.Nullable CnpjSituacaoEspecial situacaoEspecial) {
    this.situacaoEspecial = situacaoEspecial;
  }


  public CnpjEmpresa simples(@javax.annotation.Nullable CnpjOpcaoSimples simples) {
    this.simples = simples;
    return this;
  }

  /**
   * Get simples
   * @return simples
   */
  @javax.annotation.Nullable
  public CnpjOpcaoSimples getSimples() {
    return simples;
  }

  public void setSimples(@javax.annotation.Nullable CnpjOpcaoSimples simples) {
    this.simples = simples;
  }


  public CnpjEmpresa simei(@javax.annotation.Nullable CnpjOpcaoSimei simei) {
    this.simei = simei;
    return this;
  }

  /**
   * Get simei
   * @return simei
   */
  @javax.annotation.Nullable
  public CnpjOpcaoSimei getSimei() {
    return simei;
  }

  public void setSimei(@javax.annotation.Nullable CnpjOpcaoSimei simei) {
    this.simei = simei;
  }


  public CnpjEmpresa socios(@javax.annotation.Nullable List<CnpjSocio> socios) {
    this.socios = socios;
    return this;
  }

  public CnpjEmpresa addSociosItem(CnpjSocio sociosItem) {
    if (this.socios == null) {
      this.socios = new ArrayList<>();
    }
    this.socios.add(sociosItem);
    return this;
  }

  /**
   * Get socios
   * @return socios
   */
  @javax.annotation.Nullable
  public List<CnpjSocio> getSocios() {
    return socios;
  }

  public void setSocios(@javax.annotation.Nullable List<CnpjSocio> socios) {
    this.socios = socios;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CnpjEmpresa cnpjEmpresa = (CnpjEmpresa) o;
    return Objects.equals(this.cnpj, cnpjEmpresa.cnpj) &&
        Objects.equals(this.razaoSocial, cnpjEmpresa.razaoSocial) &&
        Objects.equals(this.nomeFantasia, cnpjEmpresa.nomeFantasia) &&
        Objects.equals(this.dataInicioAtividade, cnpjEmpresa.dataInicioAtividade) &&
        Objects.equals(this.matriz, cnpjEmpresa.matriz) &&
        Objects.equals(this.naturezaJuridica, cnpjEmpresa.naturezaJuridica) &&
        Objects.equals(this.capitalSocial, cnpjEmpresa.capitalSocial) &&
        Objects.equals(this.porte, cnpjEmpresa.porte) &&
        Objects.equals(this.enteFederativoResponsavel, cnpjEmpresa.enteFederativoResponsavel) &&
        Objects.equals(this.situacaoCadastral, cnpjEmpresa.situacaoCadastral) &&
        Objects.equals(this.motivoSituacaoCadastral, cnpjEmpresa.motivoSituacaoCadastral) &&
        Objects.equals(this.nomeDaCidadeNoExterior, cnpjEmpresa.nomeDaCidadeNoExterior) &&
        Objects.equals(this.pais, cnpjEmpresa.pais) &&
        Objects.equals(this.atividadePrincipal, cnpjEmpresa.atividadePrincipal) &&
        Objects.equals(this.atividadesSecundarias, cnpjEmpresa.atividadesSecundarias) &&
        Objects.equals(this.endereco, cnpjEmpresa.endereco) &&
        Objects.equals(this.telefones, cnpjEmpresa.telefones) &&
        Objects.equals(this.email, cnpjEmpresa.email) &&
        Objects.equals(this.situacaoEspecial, cnpjEmpresa.situacaoEspecial) &&
        Objects.equals(this.simples, cnpjEmpresa.simples) &&
        Objects.equals(this.simei, cnpjEmpresa.simei) &&
        Objects.equals(this.socios, cnpjEmpresa.socios);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cnpj, razaoSocial, nomeFantasia, dataInicioAtividade, matriz, naturezaJuridica, capitalSocial, porte, enteFederativoResponsavel, situacaoCadastral, motivoSituacaoCadastral, nomeDaCidadeNoExterior, pais, atividadePrincipal, atividadesSecundarias, endereco, telefones, email, situacaoEspecial, simples, simei, socios);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CnpjEmpresa {\n");
    sb.append("    cnpj: ").append(toIndentedString(cnpj)).append("\n");
    sb.append("    razaoSocial: ").append(toIndentedString(razaoSocial)).append("\n");
    sb.append("    nomeFantasia: ").append(toIndentedString(nomeFantasia)).append("\n");
    sb.append("    dataInicioAtividade: ").append(toIndentedString(dataInicioAtividade)).append("\n");
    sb.append("    matriz: ").append(toIndentedString(matriz)).append("\n");
    sb.append("    naturezaJuridica: ").append(toIndentedString(naturezaJuridica)).append("\n");
    sb.append("    capitalSocial: ").append(toIndentedString(capitalSocial)).append("\n");
    sb.append("    porte: ").append(toIndentedString(porte)).append("\n");
    sb.append("    enteFederativoResponsavel: ").append(toIndentedString(enteFederativoResponsavel)).append("\n");
    sb.append("    situacaoCadastral: ").append(toIndentedString(situacaoCadastral)).append("\n");
    sb.append("    motivoSituacaoCadastral: ").append(toIndentedString(motivoSituacaoCadastral)).append("\n");
    sb.append("    nomeDaCidadeNoExterior: ").append(toIndentedString(nomeDaCidadeNoExterior)).append("\n");
    sb.append("    pais: ").append(toIndentedString(pais)).append("\n");
    sb.append("    atividadePrincipal: ").append(toIndentedString(atividadePrincipal)).append("\n");
    sb.append("    atividadesSecundarias: ").append(toIndentedString(atividadesSecundarias)).append("\n");
    sb.append("    endereco: ").append(toIndentedString(endereco)).append("\n");
    sb.append("    telefones: ").append(toIndentedString(telefones)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    situacaoEspecial: ").append(toIndentedString(situacaoEspecial)).append("\n");
    sb.append("    simples: ").append(toIndentedString(simples)).append("\n");
    sb.append("    simei: ").append(toIndentedString(simei)).append("\n");
    sb.append("    socios: ").append(toIndentedString(socios)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cnpj");
    openapiFields.add("razao_social");
    openapiFields.add("nome_fantasia");
    openapiFields.add("data_inicio_atividade");
    openapiFields.add("matriz");
    openapiFields.add("natureza_juridica");
    openapiFields.add("capital_social");
    openapiFields.add("porte");
    openapiFields.add("ente_federativo_responsavel");
    openapiFields.add("situacao_cadastral");
    openapiFields.add("motivo_situacao_cadastral");
    openapiFields.add("nome_da_cidade_no_exterior");
    openapiFields.add("pais");
    openapiFields.add("atividade_principal");
    openapiFields.add("atividades_secundarias");
    openapiFields.add("endereco");
    openapiFields.add("telefones");
    openapiFields.add("email");
    openapiFields.add("situacao_especial");
    openapiFields.add("simples");
    openapiFields.add("simei");
    openapiFields.add("socios");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CnpjEmpresa
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CnpjEmpresa.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CnpjEmpresa is not found in the empty JSON string", CnpjEmpresa.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CnpjEmpresa.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CnpjEmpresa` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("cnpj") != null && !jsonObj.get("cnpj").isJsonNull()) && !jsonObj.get("cnpj").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cnpj` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cnpj").toString()));
      }
      if ((jsonObj.get("razao_social") != null && !jsonObj.get("razao_social").isJsonNull()) && !jsonObj.get("razao_social").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `razao_social` to be a primitive type in the JSON string but got `%s`", jsonObj.get("razao_social").toString()));
      }
      if ((jsonObj.get("nome_fantasia") != null && !jsonObj.get("nome_fantasia").isJsonNull()) && !jsonObj.get("nome_fantasia").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nome_fantasia` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nome_fantasia").toString()));
      }
      // validate the optional field `natureza_juridica`
      if (jsonObj.get("natureza_juridica") != null && !jsonObj.get("natureza_juridica").isJsonNull()) {
        CnpjNaturezaJuridica.validateJsonElement(jsonObj.get("natureza_juridica"));
      }
      // validate the optional field `porte`
      if (jsonObj.get("porte") != null && !jsonObj.get("porte").isJsonNull()) {
        CnpjPorteEmpresa.validateJsonElement(jsonObj.get("porte"));
      }
      if ((jsonObj.get("ente_federativo_responsavel") != null && !jsonObj.get("ente_federativo_responsavel").isJsonNull()) && !jsonObj.get("ente_federativo_responsavel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ente_federativo_responsavel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ente_federativo_responsavel").toString()));
      }
      // validate the optional field `situacao_cadastral`
      if (jsonObj.get("situacao_cadastral") != null && !jsonObj.get("situacao_cadastral").isJsonNull()) {
        CnpjSituacaoCadastral.validateJsonElement(jsonObj.get("situacao_cadastral"));
      }
      // validate the optional field `motivo_situacao_cadastral`
      if (jsonObj.get("motivo_situacao_cadastral") != null && !jsonObj.get("motivo_situacao_cadastral").isJsonNull()) {
        CnpjMotivoSituacaoCadastral.validateJsonElement(jsonObj.get("motivo_situacao_cadastral"));
      }
      if ((jsonObj.get("nome_da_cidade_no_exterior") != null && !jsonObj.get("nome_da_cidade_no_exterior").isJsonNull()) && !jsonObj.get("nome_da_cidade_no_exterior").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nome_da_cidade_no_exterior` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nome_da_cidade_no_exterior").toString()));
      }
      // validate the optional field `pais`
      if (jsonObj.get("pais") != null && !jsonObj.get("pais").isJsonNull()) {
        CnpjPais.validateJsonElement(jsonObj.get("pais"));
      }
      // validate the optional field `atividade_principal`
      if (jsonObj.get("atividade_principal") != null && !jsonObj.get("atividade_principal").isJsonNull()) {
        CnpjCnae.validateJsonElement(jsonObj.get("atividade_principal"));
      }
      if (jsonObj.get("atividades_secundarias") != null && !jsonObj.get("atividades_secundarias").isJsonNull()) {
        JsonArray jsonArrayatividadesSecundarias = jsonObj.getAsJsonArray("atividades_secundarias");
        if (jsonArrayatividadesSecundarias != null) {
          // ensure the json data is an array
          if (!jsonObj.get("atividades_secundarias").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `atividades_secundarias` to be an array in the JSON string but got `%s`", jsonObj.get("atividades_secundarias").toString()));
          }

          // validate the optional field `atividades_secundarias` (array)
          for (int i = 0; i < jsonArrayatividadesSecundarias.size(); i++) {
            CnpjCnaeSecundario.validateJsonElement(jsonArrayatividadesSecundarias.get(i));
          };
        }
      }
      // validate the optional field `endereco`
      if (jsonObj.get("endereco") != null && !jsonObj.get("endereco").isJsonNull()) {
        CnpjEndereco.validateJsonElement(jsonObj.get("endereco"));
      }
      if (jsonObj.get("telefones") != null && !jsonObj.get("telefones").isJsonNull()) {
        JsonArray jsonArraytelefones = jsonObj.getAsJsonArray("telefones");
        if (jsonArraytelefones != null) {
          // ensure the json data is an array
          if (!jsonObj.get("telefones").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `telefones` to be an array in the JSON string but got `%s`", jsonObj.get("telefones").toString()));
          }

          // validate the optional field `telefones` (array)
          for (int i = 0; i < jsonArraytelefones.size(); i++) {
            CnpjTelefone.validateJsonElement(jsonArraytelefones.get(i));
          };
        }
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      // validate the optional field `situacao_especial`
      if (jsonObj.get("situacao_especial") != null && !jsonObj.get("situacao_especial").isJsonNull()) {
        CnpjSituacaoEspecial.validateJsonElement(jsonObj.get("situacao_especial"));
      }
      // validate the optional field `simples`
      if (jsonObj.get("simples") != null && !jsonObj.get("simples").isJsonNull()) {
        CnpjOpcaoSimples.validateJsonElement(jsonObj.get("simples"));
      }
      // validate the optional field `simei`
      if (jsonObj.get("simei") != null && !jsonObj.get("simei").isJsonNull()) {
        CnpjOpcaoSimei.validateJsonElement(jsonObj.get("simei"));
      }
      if (jsonObj.get("socios") != null && !jsonObj.get("socios").isJsonNull()) {
        JsonArray jsonArraysocios = jsonObj.getAsJsonArray("socios");
        if (jsonArraysocios != null) {
          // ensure the json data is an array
          if (!jsonObj.get("socios").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `socios` to be an array in the JSON string but got `%s`", jsonObj.get("socios").toString()));
          }

          // validate the optional field `socios` (array)
          for (int i = 0; i < jsonArraysocios.size(); i++) {
            CnpjSocio.validateJsonElement(jsonArraysocios.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CnpjEmpresa.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CnpjEmpresa' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CnpjEmpresa> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CnpjEmpresa.class));

       return (TypeAdapter<T>) new TypeAdapter<CnpjEmpresa>() {
           @Override
           public void write(JsonWriter out, CnpjEmpresa value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CnpjEmpresa read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CnpjEmpresa given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CnpjEmpresa
   * @throws IOException if the JSON string is invalid with respect to CnpjEmpresa
   */
  public static CnpjEmpresa fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CnpjEmpresa.class);
  }

  /**
   * Convert an instance of CnpjEmpresa to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

