/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.com.caonulisses.nuvemfiscalsdk.JSON;

/**
 * Informações mais detalhadas do produto (usada na NFF).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class NfeSefazInfProdEmb {
  public static final String SERIALIZED_NAME_X_EMB = "xEmb";
  @SerializedName(SERIALIZED_NAME_X_EMB)
  @javax.annotation.Nullable
  private String xEmb;

  public static final String SERIALIZED_NAME_Q_VOL_EMB = "qVolEmb";
  @SerializedName(SERIALIZED_NAME_Q_VOL_EMB)
  @javax.annotation.Nullable
  private BigDecimal qVolEmb;

  public static final String SERIALIZED_NAME_U_EMB = "uEmb";
  @SerializedName(SERIALIZED_NAME_U_EMB)
  @javax.annotation.Nullable
  private String uEmb;

  public NfeSefazInfProdEmb() {
  }

  public NfeSefazInfProdEmb xEmb(@javax.annotation.Nullable String xEmb) {
    this.xEmb = xEmb;
    return this;
  }

  /**
   * Embalagem do produto.
   * @return xEmb
   */
  @javax.annotation.Nullable
  public String getxEmb() {
    return xEmb;
  }

  public void setxEmb(@javax.annotation.Nullable String xEmb) {
    this.xEmb = xEmb;
  }


  public NfeSefazInfProdEmb qVolEmb(@javax.annotation.Nullable BigDecimal qVolEmb) {
    this.qVolEmb = qVolEmb;
    return this;
  }

  /**
   * Volume do produto na embalagem.
   * minimum: 0
   * @return qVolEmb
   */
  @javax.annotation.Nullable
  public BigDecimal getqVolEmb() {
    return qVolEmb;
  }

  public void setqVolEmb(@javax.annotation.Nullable BigDecimal qVolEmb) {
    this.qVolEmb = qVolEmb;
  }


  public NfeSefazInfProdEmb uEmb(@javax.annotation.Nullable String uEmb) {
    this.uEmb = uEmb;
    return this;
  }

  /**
   * Unidade de Medida da Embalagem.
   * @return uEmb
   */
  @javax.annotation.Nullable
  public String getuEmb() {
    return uEmb;
  }

  public void setuEmb(@javax.annotation.Nullable String uEmb) {
    this.uEmb = uEmb;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NfeSefazInfProdEmb nfeSefazInfProdEmb = (NfeSefazInfProdEmb) o;
    return Objects.equals(this.xEmb, nfeSefazInfProdEmb.xEmb) &&
        Objects.equals(this.qVolEmb, nfeSefazInfProdEmb.qVolEmb) &&
        Objects.equals(this.uEmb, nfeSefazInfProdEmb.uEmb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(xEmb, qVolEmb, uEmb);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NfeSefazInfProdEmb {\n");
    sb.append("    xEmb: ").append(toIndentedString(xEmb)).append("\n");
    sb.append("    qVolEmb: ").append(toIndentedString(qVolEmb)).append("\n");
    sb.append("    uEmb: ").append(toIndentedString(uEmb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("xEmb");
    openapiFields.add("qVolEmb");
    openapiFields.add("uEmb");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("xEmb");
    openapiRequiredFields.add("qVolEmb");
    openapiRequiredFields.add("uEmb");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NfeSefazInfProdEmb
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NfeSefazInfProdEmb.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NfeSefazInfProdEmb is not found in the empty JSON string", NfeSefazInfProdEmb.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NfeSefazInfProdEmb.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NfeSefazInfProdEmb` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NfeSefazInfProdEmb.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("xEmb") != null && !jsonObj.get("xEmb").isJsonNull()) && !jsonObj.get("xEmb").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `xEmb` to be a primitive type in the JSON string but got `%s`", jsonObj.get("xEmb").toString()));
      }
      if ((jsonObj.get("uEmb") != null && !jsonObj.get("uEmb").isJsonNull()) && !jsonObj.get("uEmb").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uEmb` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uEmb").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NfeSefazInfProdEmb.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NfeSefazInfProdEmb' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NfeSefazInfProdEmb> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NfeSefazInfProdEmb.class));

       return (TypeAdapter<T>) new TypeAdapter<NfeSefazInfProdEmb>() {
           @Override
           public void write(JsonWriter out, NfeSefazInfProdEmb value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NfeSefazInfProdEmb read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NfeSefazInfProdEmb given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NfeSefazInfProdEmb
   * @throws IOException if the JSON string is invalid with respect to NfeSefazInfProdEmb
   */
  public static NfeSefazInfProdEmb fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NfeSefazInfProdEmb.class);
  }

  /**
   * Convert an instance of NfeSefazInfProdEmb to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

