/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.com.caonulisses.nuvemfiscalsdk.JSON;

/**
 * Dados da fatura.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class NfeSefazFat {
  public static final String SERIALIZED_NAME_N_FAT = "nFat";
  @SerializedName(SERIALIZED_NAME_N_FAT)
  @javax.annotation.Nullable
  private String nFat;

  public static final String SERIALIZED_NAME_V_ORIG = "vOrig";
  @SerializedName(SERIALIZED_NAME_V_ORIG)
  @javax.annotation.Nullable
  private BigDecimal vOrig;

  public static final String SERIALIZED_NAME_V_DESC = "vDesc";
  @SerializedName(SERIALIZED_NAME_V_DESC)
  @javax.annotation.Nullable
  private BigDecimal vDesc;

  public static final String SERIALIZED_NAME_V_LIQ = "vLiq";
  @SerializedName(SERIALIZED_NAME_V_LIQ)
  @javax.annotation.Nullable
  private BigDecimal vLiq;

  public NfeSefazFat() {
  }

  public NfeSefazFat nFat(@javax.annotation.Nullable String nFat) {
    this.nFat = nFat;
    return this;
  }

  /**
   * Número da fatura.
   * @return nFat
   */
  @javax.annotation.Nullable
  public String getnFat() {
    return nFat;
  }

  public void setnFat(@javax.annotation.Nullable String nFat) {
    this.nFat = nFat;
  }


  public NfeSefazFat vOrig(@javax.annotation.Nullable BigDecimal vOrig) {
    this.vOrig = vOrig;
    return this;
  }

  /**
   * Valor original da fatura.
   * minimum: 0
   * @return vOrig
   */
  @javax.annotation.Nullable
  public BigDecimal getvOrig() {
    return vOrig;
  }

  public void setvOrig(@javax.annotation.Nullable BigDecimal vOrig) {
    this.vOrig = vOrig;
  }


  public NfeSefazFat vDesc(@javax.annotation.Nullable BigDecimal vDesc) {
    this.vDesc = vDesc;
    return this;
  }

  /**
   * Valor do desconto da fatura.
   * minimum: 0
   * @return vDesc
   */
  @javax.annotation.Nullable
  public BigDecimal getvDesc() {
    return vDesc;
  }

  public void setvDesc(@javax.annotation.Nullable BigDecimal vDesc) {
    this.vDesc = vDesc;
  }


  public NfeSefazFat vLiq(@javax.annotation.Nullable BigDecimal vLiq) {
    this.vLiq = vLiq;
    return this;
  }

  /**
   * Valor líquido da fatura.
   * minimum: 0
   * @return vLiq
   */
  @javax.annotation.Nullable
  public BigDecimal getvLiq() {
    return vLiq;
  }

  public void setvLiq(@javax.annotation.Nullable BigDecimal vLiq) {
    this.vLiq = vLiq;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NfeSefazFat nfeSefazFat = (NfeSefazFat) o;
    return Objects.equals(this.nFat, nfeSefazFat.nFat) &&
        Objects.equals(this.vOrig, nfeSefazFat.vOrig) &&
        Objects.equals(this.vDesc, nfeSefazFat.vDesc) &&
        Objects.equals(this.vLiq, nfeSefazFat.vLiq);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(nFat, vOrig, vDesc, vLiq);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NfeSefazFat {\n");
    sb.append("    nFat: ").append(toIndentedString(nFat)).append("\n");
    sb.append("    vOrig: ").append(toIndentedString(vOrig)).append("\n");
    sb.append("    vDesc: ").append(toIndentedString(vDesc)).append("\n");
    sb.append("    vLiq: ").append(toIndentedString(vLiq)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nFat");
    openapiFields.add("vOrig");
    openapiFields.add("vDesc");
    openapiFields.add("vLiq");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NfeSefazFat
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NfeSefazFat.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NfeSefazFat is not found in the empty JSON string", NfeSefazFat.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NfeSefazFat.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NfeSefazFat` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nFat") != null && !jsonObj.get("nFat").isJsonNull()) && !jsonObj.get("nFat").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nFat` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nFat").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NfeSefazFat.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NfeSefazFat' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NfeSefazFat> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NfeSefazFat.class));

       return (TypeAdapter<T>) new TypeAdapter<NfeSefazFat>() {
           @Override
           public void write(JsonWriter out, NfeSefazFat value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NfeSefazFat read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NfeSefazFat given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NfeSefazFat
   * @throws IOException if the JSON string is invalid with respect to NfeSefazFat
   */
  public static NfeSefazFat fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NfeSefazFat.class);
  }

  /**
   * Convert an instance of NfeSefazFat to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

