/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CnpjTelefone
 */
public class CnpjTelefoneTest {
    private final CnpjTelefone model = new CnpjTelefone();

    /**
     * Model tests for CnpjTelefone
     */
    @Test
    public void testCnpjTelefone() {
        // TODO: test CnpjTelefone
    }

    /**
     * Test the property 'ddd'
     */
    @Test
    public void dddTest() {
        // TODO: test ddd
    }

    /**
     * Test the property 'numero'
     */
    @Test
    public void numeroTest() {
        // TODO: test numero
    }

}
