/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.CnpjMunicipio;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CnpjEndereco
 */
public class CnpjEnderecoTest {
    private final CnpjEndereco model = new CnpjEndereco();

    /**
     * Model tests for CnpjEndereco
     */
    @Test
    public void testCnpjEndereco() {
        // TODO: test CnpjEndereco
    }

    /**
     * Test the property 'tipoLogradouro'
     */
    @Test
    public void tipoLogradouroTest() {
        // TODO: test tipoLogradouro
    }

    /**
     * Test the property 'logradouro'
     */
    @Test
    public void logradouroTest() {
        // TODO: test logradouro
    }

    /**
     * Test the property 'numero'
     */
    @Test
    public void numeroTest() {
        // TODO: test numero
    }

    /**
     * Test the property 'complemento'
     */
    @Test
    public void complementoTest() {
        // TODO: test complemento
    }

    /**
     * Test the property 'bairro'
     */
    @Test
    public void bairroTest() {
        // TODO: test bairro
    }

    /**
     * Test the property 'cep'
     */
    @Test
    public void cepTest() {
        // TODO: test cep
    }

    /**
     * Test the property 'uf'
     */
    @Test
    public void ufTest() {
        // TODO: test uf
    }

    /**
     * Test the property 'municipio'
     */
    @Test
    public void municipioTest() {
        // TODO: test municipio
    }

}
