/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CteInfCorrecao
 */
public class CteInfCorrecaoTest {
    private final CteInfCorrecao model = new CteInfCorrecao();

    /**
     * Model tests for CteInfCorrecao
     */
    @Test
    public void testCteInfCorrecao() {
        // TODO: test CteInfCorrecao
    }

    /**
     * Test the property 'grupoAlterado'
     */
    @Test
    public void grupoAlteradoTest() {
        // TODO: test grupoAlterado
    }

    /**
     * Test the property 'campoAlterado'
     */
    @Test
    public void campoAlteradoTest() {
        // TODO: test campoAlterado
    }

    /**
     * Test the property 'valorAlterado'
     */
    @Test
    public void valorAlteradoTest() {
        // TODO: test valorAlterado
    }

    /**
     * Test the property 'numeroItemAlterado'
     */
    @Test
    public void numeroItemAlteradoTest() {
        // TODO: test numeroItemAlterado
    }

}
