/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazLacUnidCarga;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CteSefazUnidCarga
 */
public class CteSefazUnidCargaTest {
    private final CteSefazUnidCarga model = new CteSefazUnidCarga();

    /**
     * Model tests for CteSefazUnidCarga
     */
    @Test
    public void testCteSefazUnidCarga() {
        // TODO: test CteSefazUnidCarga
    }

    /**
     * Test the property 'tpUnidCarga'
     */
    @Test
    public void tpUnidCargaTest() {
        // TODO: test tpUnidCarga
    }

    /**
     * Test the property 'idUnidCarga'
     */
    @Test
    public void idUnidCargaTest() {
        // TODO: test idUnidCarga
    }

    /**
     * Test the property 'lacUnidCarga'
     */
    @Test
    public void lacUnidCargaTest() {
        // TODO: test lacUnidCarga
    }

    /**
     * Test the property 'qtdRat'
     */
    @Test
    public void qtdRatTest() {
        // TODO: test qtdRat
    }

}
