/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazOcc;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CteSefazRodo
 */
public class CteSefazRodoTest {
    private final CteSefazRodo model = new CteSefazRodo();

    /**
     * Model tests for CteSefazRodo
     */
    @Test
    public void testCteSefazRodo() {
        // TODO: test CteSefazRodo
    }

    /**
     * Test the property 'RNTRC'
     */
    @Test
    public void RNTRCTest() {
        // TODO: test RNTRC
    }

    /**
     * Test the property 'occ'
     */
    @Test
    public void occTest() {
        // TODO: test occ
    }

}
