/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazInfSeg;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CteSefazSeg
 */
public class CteSefazSegTest {
    private final CteSefazSeg model = new CteSefazSeg();

    /**
     * Model tests for CteSefazSeg
     */
    @Test
    public void testCteSefazSeg() {
        // TODO: test CteSefazSeg
    }

    /**
     * Test the property 'infSeg'
     */
    @Test
    public void infSegTest() {
        // TODO: test infSeg
    }

    /**
     * Test the property 'nApol'
     */
    @Test
    public void nApolTest() {
        // TODO: test nApol
    }

    /**
     * Test the property 'nAver'
     */
    @Test
    public void nAverTest() {
        // TODO: test nAver
    }

}
