/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMS00;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMS20;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMS45;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMS60;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMS90;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMSOutraUF;
import io.github.com.caonulisses.nuvemfiscalsdk.model.CteSefazICMSSN;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CteSefazImp
 */
public class CteSefazImpTest {
    private final CteSefazImp model = new CteSefazImp();

    /**
     * Model tests for CteSefazImp
     */
    @Test
    public void testCteSefazImp() {
        // TODO: test CteSefazImp
    }

    /**
     * Test the property 'ICMS00'
     */
    @Test
    public void ICMS00Test() {
        // TODO: test ICMS00
    }

    /**
     * Test the property 'ICMS20'
     */
    @Test
    public void ICMS20Test() {
        // TODO: test ICMS20
    }

    /**
     * Test the property 'ICMS45'
     */
    @Test
    public void ICMS45Test() {
        // TODO: test ICMS45
    }

    /**
     * Test the property 'ICMS60'
     */
    @Test
    public void ICMS60Test() {
        // TODO: test ICMS60
    }

    /**
     * Test the property 'ICMS90'
     */
    @Test
    public void ICMS90Test() {
        // TODO: test ICMS90
    }

    /**
     * Test the property 'icMSOutraUF'
     */
    @Test
    public void icMSOutraUFTest() {
        // TODO: test icMSOutraUF
    }

    /**
     * Test the property 'ICMSSN'
     */
    @Test
    public void ICMSSNTest() {
        // TODO: test ICMSSN
    }

}
