/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.DfeAutorEvento;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DfeInutilizacao
 */
public class DfeInutilizacaoTest {
    private final DfeInutilizacao model = new DfeInutilizacao();

    /**
     * Model tests for DfeInutilizacao
     */
    @Test
    public void testDfeInutilizacao() {
        // TODO: test DfeInutilizacao
    }

    /**
     * Test the property 'cnpj'
     */
    @Test
    public void cnpjTest() {
        // TODO: test cnpj
    }

    /**
     * Test the property 'ano'
     */
    @Test
    public void anoTest() {
        // TODO: test ano
    }

    /**
     * Test the property 'modelo'
     */
    @Test
    public void modeloTest() {
        // TODO: test modelo
    }

    /**
     * Test the property 'serie'
     */
    @Test
    public void serieTest() {
        // TODO: test serie
    }

    /**
     * Test the property 'numeroInicial'
     */
    @Test
    public void numeroInicialTest() {
        // TODO: test numeroInicial
    }

    /**
     * Test the property 'numeroFinal'
     */
    @Test
    public void numeroFinalTest() {
        // TODO: test numeroFinal
    }

    /**
     * Test the property 'justificativa'
     */
    @Test
    public void justificativaTest() {
        // TODO: test justificativa
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ambiente'
     */
    @Test
    public void ambienteTest() {
        // TODO: test ambiente
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'autor'
     */
    @Test
    public void autorTest() {
        // TODO: test autor
    }

    /**
     * Test the property 'chaveAcesso'
     */
    @Test
    public void chaveAcessoTest() {
        // TODO: test chaveAcesso
    }

    /**
     * Test the property 'dataEvento'
     */
    @Test
    public void dataEventoTest() {
        // TODO: test dataEvento
    }

    /**
     * Test the property 'numeroSequencial'
     */
    @Test
    public void numeroSequencialTest() {
        // TODO: test numeroSequencial
    }

    /**
     * Test the property 'dataRecebimento'
     */
    @Test
    public void dataRecebimentoTest() {
        // TODO: test dataRecebimento
    }

    /**
     * Test the property 'codigoStatus'
     */
    @Test
    public void codigoStatusTest() {
        // TODO: test codigoStatus
    }

    /**
     * Test the property 'motivoStatus'
     */
    @Test
    public void motivoStatusTest() {
        // TODO: test motivoStatus
    }

    /**
     * Test the property 'numeroProtocolo'
     */
    @Test
    public void numeroProtocoloTest() {
        // TODO: test numeroProtocolo
    }

    /**
     * Test the property 'codigoMensagem'
     */
    @Test
    public void codigoMensagemTest() {
        // TODO: test codigoMensagem
    }

    /**
     * Test the property 'mensagem'
     */
    @Test
    public void mensagemTest() {
        // TODO: test mensagem
    }

    /**
     * Test the property 'tipoEvento'
     */
    @Test
    public void tipoEventoTest() {
        // TODO: test tipoEvento
    }

}
