/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MdfeSefazLacUnidTransp;
import org.openapitools.client.model.MdfeSefazUnidCarga;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MdfeSefazUnidadeTransp
 */
public class MdfeSefazUnidadeTranspTest {
    private final MdfeSefazUnidadeTransp model = new MdfeSefazUnidadeTransp();

    /**
     * Model tests for MdfeSefazUnidadeTransp
     */
    @Test
    public void testMdfeSefazUnidadeTransp() {
        // TODO: test MdfeSefazUnidadeTransp
    }

    /**
     * Test the property 'tpUnidTransp'
     */
    @Test
    public void tpUnidTranspTest() {
        // TODO: test tpUnidTransp
    }

    /**
     * Test the property 'idUnidTransp'
     */
    @Test
    public void idUnidTranspTest() {
        // TODO: test idUnidTransp
    }

    /**
     * Test the property 'lacUnidTransp'
     */
    @Test
    public void lacUnidTranspTest() {
        // TODO: test lacUnidTransp
    }

    /**
     * Test the property 'infUnidCarga'
     */
    @Test
    public void infUnidCargaTest() {
        // TODO: test infUnidCarga
    }

    /**
     * Test the property 'qtdRat'
     */
    @Test
    public void qtdRatTest() {
        // TODO: test qtdRat
    }

}
