/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfcomSefazICMSTot;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfcomSefazVRetTribTot;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfcomSefazTotal
 */
public class NfcomSefazTotalTest {
    private final NfcomSefazTotal model = new NfcomSefazTotal();

    /**
     * Model tests for NfcomSefazTotal
     */
    @Test
    public void testNfcomSefazTotal() {
        // TODO: test NfcomSefazTotal
    }

    /**
     * Test the property 'vProd'
     */
    @Test
    public void vProdTest() {
        // TODO: test vProd
    }

    /**
     * Test the property 'icMSTot'
     */
    @Test
    public void icMSTotTest() {
        // TODO: test icMSTot
    }

    /**
     * Test the property 'vCOFINS'
     */
    @Test
    public void vCOFINSTest() {
        // TODO: test vCOFINS
    }

    /**
     * Test the property 'vPIS'
     */
    @Test
    public void vPISTest() {
        // TODO: test vPIS
    }

    /**
     * Test the property 'vFUNTTEL'
     */
    @Test
    public void vFUNTTELTest() {
        // TODO: test vFUNTTEL
    }

    /**
     * Test the property 'vFUST'
     */
    @Test
    public void vFUSTTest() {
        // TODO: test vFUST
    }

    /**
     * Test the property 'vRetTribTot'
     */
    @Test
    public void vRetTribTotTest() {
        // TODO: test vRetTribTot
    }

    /**
     * Test the property 'vDesc'
     */
    @Test
    public void vDescTest() {
        // TODO: test vDesc
    }

    /**
     * Test the property 'vOutro'
     */
    @Test
    public void vOutroTest() {
        // TODO: test vOutro
    }

    /**
     * Test the property 'vNF'
     */
    @Test
    public void vNFTest() {
        // TODO: test vNF
    }

}
