/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.NfcomSefazGProc;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfcomSefazGProcRef
 */
public class NfcomSefazGProcRefTest {
    private final NfcomSefazGProcRef model = new NfcomSefazGProcRef();

    /**
     * Model tests for NfcomSefazGProcRef
     */
    @Test
    public void testNfcomSefazGProcRef() {
        // TODO: test NfcomSefazGProcRef
    }

    /**
     * Test the property 'vItem'
     */
    @Test
    public void vItemTest() {
        // TODO: test vItem
    }

    /**
     * Test the property 'qFaturada'
     */
    @Test
    public void qFaturadaTest() {
        // TODO: test qFaturada
    }

    /**
     * Test the property 'vProd'
     */
    @Test
    public void vProdTest() {
        // TODO: test vProd
    }

    /**
     * Test the property 'vDesc'
     */
    @Test
    public void vDescTest() {
        // TODO: test vDesc
    }

    /**
     * Test the property 'vOutro'
     */
    @Test
    public void vOutroTest() {
        // TODO: test vOutro
    }

    /**
     * Test the property 'indDevolucao'
     */
    @Test
    public void indDevolucaoTest() {
        // TODO: test indDevolucao
    }

    /**
     * Test the property 'vBC'
     */
    @Test
    public void vBCTest() {
        // TODO: test vBC
    }

    /**
     * Test the property 'pICMS'
     */
    @Test
    public void pICMSTest() {
        // TODO: test pICMS
    }

    /**
     * Test the property 'vICMS'
     */
    @Test
    public void vICMSTest() {
        // TODO: test vICMS
    }

    /**
     * Test the property 'vPIS'
     */
    @Test
    public void vPISTest() {
        // TODO: test vPIS
    }

    /**
     * Test the property 'vCOFINS'
     */
    @Test
    public void vCOFINSTest() {
        // TODO: test vCOFINS
    }

    /**
     * Test the property 'vFCP'
     */
    @Test
    public void vFCPTest() {
        // TODO: test vFCP
    }

    /**
     * Test the property 'gProc'
     */
    @Test
    public void gProcTest() {
        // TODO: test gProc
    }

}
