/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazCIDE;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazEncerrante;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazOrigComb;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazComb
 */
public class NfeSefazCombTest {
    private final NfeSefazComb model = new NfeSefazComb();

    /**
     * Model tests for NfeSefazComb
     */
    @Test
    public void testNfeSefazComb() {
        // TODO: test NfeSefazComb
    }

    /**
     * Test the property 'cProdANP'
     */
    @Test
    public void cProdANPTest() {
        // TODO: test cProdANP
    }

    /**
     * Test the property 'descANP'
     */
    @Test
    public void descANPTest() {
        // TODO: test descANP
    }

    /**
     * Test the property 'pGLP'
     */
    @Test
    public void pGLPTest() {
        // TODO: test pGLP
    }

    /**
     * Test the property 'pGNn'
     */
    @Test
    public void pGNnTest() {
        // TODO: test pGNn
    }

    /**
     * Test the property 'pGNi'
     */
    @Test
    public void pGNiTest() {
        // TODO: test pGNi
    }

    /**
     * Test the property 'vPart'
     */
    @Test
    public void vPartTest() {
        // TODO: test vPart
    }

    /**
     * Test the property 'CODIF'
     */
    @Test
    public void CODIFTest() {
        // TODO: test CODIF
    }

    /**
     * Test the property 'qTemp'
     */
    @Test
    public void qTempTest() {
        // TODO: test qTemp
    }

    /**
     * Test the property 'ufCons'
     */
    @Test
    public void ufConsTest() {
        // TODO: test ufCons
    }

    /**
     * Test the property 'CIDE'
     */
    @Test
    public void CIDETest() {
        // TODO: test CIDE
    }

    /**
     * Test the property 'encerrante'
     */
    @Test
    public void encerranteTest() {
        // TODO: test encerrante
    }

    /**
     * Test the property 'pBio'
     */
    @Test
    public void pBioTest() {
        // TODO: test pBio
    }

    /**
     * Test the property 'origComb'
     */
    @Test
    public void origCombTest() {
        // TODO: test origComb
    }

}
