/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazEnderEmi;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazEmit
 */
public class NfeSefazEmitTest {
    private final NfeSefazEmit model = new NfeSefazEmit();

    /**
     * Model tests for NfeSefazEmit
     */
    @Test
    public void testNfeSefazEmit() {
        // TODO: test NfeSefazEmit
    }

    /**
     * Test the property 'CNPJ'
     */
    @Test
    public void CNPJTest() {
        // TODO: test CNPJ
    }

    /**
     * Test the property 'CPF'
     */
    @Test
    public void CPFTest() {
        // TODO: test CPF
    }

    /**
     * Test the property 'xNome'
     */
    @Test
    public void xNomeTest() {
        // TODO: test xNome
    }

    /**
     * Test the property 'xFant'
     */
    @Test
    public void xFantTest() {
        // TODO: test xFant
    }

    /**
     * Test the property 'enderEmit'
     */
    @Test
    public void enderEmitTest() {
        // TODO: test enderEmit
    }

    /**
     * Test the property 'IE'
     */
    @Test
    public void IETest() {
        // TODO: test IE
    }

    /**
     * Test the property 'IEST'
     */
    @Test
    public void IESTTest() {
        // TODO: test IEST
    }

    /**
     * Test the property 'IM'
     */
    @Test
    public void IMTest() {
        // TODO: test IM
    }

    /**
     * Test the property 'CNAE'
     */
    @Test
    public void CNAETest() {
        // TODO: test CNAE
    }

    /**
     * Test the property 'CRT'
     */
    @Test
    public void CRTTest() {
        // TODO: test CRT
    }

}
