/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazMed
 */
public class NfeSefazMedTest {
    private final NfeSefazMed model = new NfeSefazMed();

    /**
     * Model tests for NfeSefazMed
     */
    @Test
    public void testNfeSefazMed() {
        // TODO: test NfeSefazMed
    }

    /**
     * Test the property 'cProdANVISA'
     */
    @Test
    public void cProdANVISATest() {
        // TODO: test cProdANVISA
    }

    /**
     * Test the property 'xMotivoIsencao'
     */
    @Test
    public void xMotivoIsencaoTest() {
        // TODO: test xMotivoIsencao
    }

    /**
     * Test the property 'vPMC'
     */
    @Test
    public void vPMCTest() {
        // TODO: test vPMC
    }

}
