/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.NfeSefazPISAliq;
import org.openapitools.client.model.NfeSefazPISNT;
import org.openapitools.client.model.NfeSefazPISOutr;
import org.openapitools.client.model.NfeSefazPISQtde;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazPIS
 */
public class NfeSefazPISTest {
    private final NfeSefazPIS model = new NfeSefazPIS();

    /**
     * Model tests for NfeSefazPIS
     */
    @Test
    public void testNfeSefazPIS() {
        // TODO: test NfeSefazPIS
    }

    /**
     * Test the property 'piSAliq'
     */
    @Test
    public void piSAliqTest() {
        // TODO: test piSAliq
    }

    /**
     * Test the property 'piSQtde'
     */
    @Test
    public void piSQtdeTest() {
        // TODO: test piSQtde
    }

    /**
     * Test the property 'PISNT'
     */
    @Test
    public void PISNTTest() {
        // TODO: test PISNT
    }

    /**
     * Test the property 'piSOutr'
     */
    @Test
    public void piSOutrTest() {
        // TODO: test piSOutr
    }

}
