/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazPISOutr
 */
public class NfeSefazPISOutrTest {
    private final NfeSefazPISOutr model = new NfeSefazPISOutr();

    /**
     * Model tests for NfeSefazPISOutr
     */
    @Test
    public void testNfeSefazPISOutr() {
        // TODO: test NfeSefazPISOutr
    }

    /**
     * Test the property 'CST'
     */
    @Test
    public void CSTTest() {
        // TODO: test CST
    }

    /**
     * Test the property 'vBC'
     */
    @Test
    public void vBCTest() {
        // TODO: test vBC
    }

    /**
     * Test the property 'pPIS'
     */
    @Test
    public void pPISTest() {
        // TODO: test pPIS
    }

    /**
     * Test the property 'qBCProd'
     */
    @Test
    public void qBCProdTest() {
        // TODO: test qBCProd
    }

    /**
     * Test the property 'vAliqProd'
     */
    @Test
    public void vAliqProdTest() {
        // TODO: test vAliqProd
    }

    /**
     * Test the property 'vPIS'
     */
    @Test
    public void vPISTest() {
        // TODO: test vPIS
    }

}
