/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazPISNT
 */
public class NfeSefazPISNTTest {
    private final NfeSefazPISNT model = new NfeSefazPISNT();

    /**
     * Model tests for NfeSefazPISNT
     */
    @Test
    public void testNfeSefazPISNT() {
        // TODO: test NfeSefazPISNT
    }

    /**
     * Test the property 'CST'
     */
    @Test
    public void CSTTest() {
        // TODO: test CST
    }

}
