/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazImposto;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazImpostoDevol;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazObsItem;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfeSefazProd;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazDet
 */
public class NfeSefazDetTest {
    private final NfeSefazDet model = new NfeSefazDet();

    /**
     * Model tests for NfeSefazDet
     */
    @Test
    public void testNfeSefazDet() {
        // TODO: test NfeSefazDet
    }

    /**
     * Test the property 'nItem'
     */
    @Test
    public void nItemTest() {
        // TODO: test nItem
    }

    /**
     * Test the property 'prod'
     */
    @Test
    public void prodTest() {
        // TODO: test prod
    }

    /**
     * Test the property 'imposto'
     */
    @Test
    public void impostoTest() {
        // TODO: test imposto
    }

    /**
     * Test the property 'impostoDevol'
     */
    @Test
    public void impostoDevolTest() {
        // TODO: test impostoDevol
    }

    /**
     * Test the property 'infAdProd'
     */
    @Test
    public void infAdProdTest() {
        // TODO: test infAdProd
    }

    /**
     * Test the property 'obsItem'
     */
    @Test
    public void obsItemTest() {
        // TODO: test obsItem
    }

}
