/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.NfeSefazICMS00;
import org.openapitools.client.model.NfeSefazICMS02;
import org.openapitools.client.model.NfeSefazICMS10;
import org.openapitools.client.model.NfeSefazICMS15;
import org.openapitools.client.model.NfeSefazICMS20;
import org.openapitools.client.model.NfeSefazICMS30;
import org.openapitools.client.model.NfeSefazICMS40;
import org.openapitools.client.model.NfeSefazICMS51;
import org.openapitools.client.model.NfeSefazICMS53;
import org.openapitools.client.model.NfeSefazICMS60;
import org.openapitools.client.model.NfeSefazICMS61;
import org.openapitools.client.model.NfeSefazICMS70;
import org.openapitools.client.model.NfeSefazICMS90;
import org.openapitools.client.model.NfeSefazICMSPart;
import org.openapitools.client.model.NfeSefazICMSSN101;
import org.openapitools.client.model.NfeSefazICMSSN102;
import org.openapitools.client.model.NfeSefazICMSSN201;
import org.openapitools.client.model.NfeSefazICMSSN202;
import org.openapitools.client.model.NfeSefazICMSSN500;
import org.openapitools.client.model.NfeSefazICMSSN900;
import org.openapitools.client.model.NfeSefazICMSST;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazICMS
 */
public class NfeSefazICMSTest {
    private final NfeSefazICMS model = new NfeSefazICMS();

    /**
     * Model tests for NfeSefazICMS
     */
    @Test
    public void testNfeSefazICMS() {
        // TODO: test NfeSefazICMS
    }

    /**
     * Test the property 'ICMS00'
     */
    @Test
    public void ICMS00Test() {
        // TODO: test ICMS00
    }

    /**
     * Test the property 'ICMS02'
     */
    @Test
    public void ICMS02Test() {
        // TODO: test ICMS02
    }

    /**
     * Test the property 'ICMS10'
     */
    @Test
    public void ICMS10Test() {
        // TODO: test ICMS10
    }

    /**
     * Test the property 'ICMS15'
     */
    @Test
    public void ICMS15Test() {
        // TODO: test ICMS15
    }

    /**
     * Test the property 'ICMS20'
     */
    @Test
    public void ICMS20Test() {
        // TODO: test ICMS20
    }

    /**
     * Test the property 'ICMS30'
     */
    @Test
    public void ICMS30Test() {
        // TODO: test ICMS30
    }

    /**
     * Test the property 'ICMS40'
     */
    @Test
    public void ICMS40Test() {
        // TODO: test ICMS40
    }

    /**
     * Test the property 'ICMS51'
     */
    @Test
    public void ICMS51Test() {
        // TODO: test ICMS51
    }

    /**
     * Test the property 'ICMS53'
     */
    @Test
    public void ICMS53Test() {
        // TODO: test ICMS53
    }

    /**
     * Test the property 'ICMS60'
     */
    @Test
    public void ICMS60Test() {
        // TODO: test ICMS60
    }

    /**
     * Test the property 'ICMS61'
     */
    @Test
    public void ICMS61Test() {
        // TODO: test ICMS61
    }

    /**
     * Test the property 'ICMS70'
     */
    @Test
    public void ICMS70Test() {
        // TODO: test ICMS70
    }

    /**
     * Test the property 'ICMS90'
     */
    @Test
    public void ICMS90Test() {
        // TODO: test ICMS90
    }

    /**
     * Test the property 'icMSPart'
     */
    @Test
    public void icMSPartTest() {
        // TODO: test icMSPart
    }

    /**
     * Test the property 'ICMSST'
     */
    @Test
    public void ICMSSTTest() {
        // TODO: test ICMSST
    }

    /**
     * Test the property 'ICMSSN101'
     */
    @Test
    public void ICMSSN101Test() {
        // TODO: test ICMSSN101
    }

    /**
     * Test the property 'ICMSSN102'
     */
    @Test
    public void ICMSSN102Test() {
        // TODO: test ICMSSN102
    }

    /**
     * Test the property 'ICMSSN201'
     */
    @Test
    public void ICMSSN201Test() {
        // TODO: test ICMSSN201
    }

    /**
     * Test the property 'ICMSSN202'
     */
    @Test
    public void ICMSSN202Test() {
        // TODO: test ICMSSN202
    }

    /**
     * Test the property 'ICMSSN500'
     */
    @Test
    public void ICMSSN500Test() {
        // TODO: test ICMSSN500
    }

    /**
     * Test the property 'ICMSSN900'
     */
    @Test
    public void ICMSSN900Test() {
        // TODO: test ICMSSN900
    }

}
