/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NfeSefazICMSSN500
 */
public class NfeSefazICMSSN500Test {
    private final NfeSefazICMSSN500 model = new NfeSefazICMSSN500();

    /**
     * Model tests for NfeSefazICMSSN500
     */
    @Test
    public void testNfeSefazICMSSN500() {
        // TODO: test NfeSefazICMSSN500
    }

    /**
     * Test the property 'orig'
     */
    @Test
    public void origTest() {
        // TODO: test orig
    }

    /**
     * Test the property 'CSOSN'
     */
    @Test
    public void CSOSNTest() {
        // TODO: test CSOSN
    }

    /**
     * Test the property 'vBCSTRet'
     */
    @Test
    public void vBCSTRetTest() {
        // TODO: test vBCSTRet
    }

    /**
     * Test the property 'pST'
     */
    @Test
    public void pSTTest() {
        // TODO: test pST
    }

    /**
     * Test the property 'vICMSSubstituto'
     */
    @Test
    public void vICMSSubstitutoTest() {
        // TODO: test vICMSSubstituto
    }

    /**
     * Test the property 'vICMSSTRet'
     */
    @Test
    public void vICMSSTRetTest() {
        // TODO: test vICMSSTRet
    }

    /**
     * Test the property 'vBCFCPSTRet'
     */
    @Test
    public void vBCFCPSTRetTest() {
        // TODO: test vBCFCPSTRet
    }

    /**
     * Test the property 'pFCPSTRet'
     */
    @Test
    public void pFCPSTRetTest() {
        // TODO: test pFCPSTRet
    }

    /**
     * Test the property 'vFCPSTRet'
     */
    @Test
    public void vFCPSTRetTest() {
        // TODO: test vFCPSTRet
    }

    /**
     * Test the property 'pRedBCEfet'
     */
    @Test
    public void pRedBCEfetTest() {
        // TODO: test pRedBCEfet
    }

    /**
     * Test the property 'vBCEfet'
     */
    @Test
    public void vBCEfetTest() {
        // TODO: test vBCEfet
    }

    /**
     * Test the property 'pICMSEfet'
     */
    @Test
    public void pICMSEfetTest() {
        // TODO: test pICMSEfet
    }

    /**
     * Test the property 'vICMSEfet'
     */
    @Test
    public void vICMSEfetTest() {
        // TODO: test vICMSEfet
    }

}
