/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import io.github.com.caonulisses.nuvemfiscalsdk.model.DPS;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfseCancelamento;
import io.github.com.caonulisses.nuvemfiscalsdk.model.NfseMensagemRetorno;
import io.github.com.caonulisses.nuvemfiscalsdk.model.Rps;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Nfse
 */
public class NfseTest {
    private final Nfse model = new Nfse();

    /**
     * Model tests for Nfse
     */
    @Test
    public void testNfse() {
        // TODO: test Nfse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'numero'
     */
    @Test
    public void numeroTest() {
        // TODO: test numero
    }

    /**
     * Test the property 'codigoVerificacao'
     */
    @Test
    public void codigoVerificacaoTest() {
        // TODO: test codigoVerificacao
    }

    /**
     * Test the property 'linkUrl'
     */
    @Test
    public void linkUrlTest() {
        // TODO: test linkUrl
    }

    /**
     * Test the property 'dataEmissao'
     */
    @Test
    public void dataEmissaoTest() {
        // TODO: test dataEmissao
    }

    /**
     * Test the property 'ambiente'
     */
    @Test
    public void ambienteTest() {
        // TODO: test ambiente
    }

    /**
     * Test the property 'referencia'
     */
    @Test
    public void referenciaTest() {
        // TODO: test referencia
    }

    /**
     * Test the property 'dps'
     */
    @Test
    public void dpsTest() {
        // TODO: test dps
    }

    /**
     * Test the property 'cancelamento'
     */
    @Test
    public void cancelamentoTest() {
        // TODO: test cancelamento
    }

    /**
     * Test the property 'mensagens'
     */
    @Test
    public void mensagensTest() {
        // TODO: test mensagens
    }

    /**
     * Test the property 'declaracaoPrestacaoServico'
     */
    @Test
    public void declaracaoPrestacaoServicoTest() {
        // TODO: test declaracaoPrestacaoServico
    }

}
