/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RpsServicoValores
 */
public class RpsServicoValoresTest {
    private final RpsServicoValores model = new RpsServicoValores();

    /**
     * Model tests for RpsServicoValores
     */
    @Test
    public void testRpsServicoValores() {
        // TODO: test RpsServicoValores
    }

    /**
     * Test the property 'valorUnitario'
     */
    @Test
    public void valorUnitarioTest() {
        // TODO: test valorUnitario
    }

    /**
     * Test the property 'valorServicos'
     */
    @Test
    public void valorServicosTest() {
        // TODO: test valorServicos
    }

    /**
     * Test the property 'valorDeducoes'
     */
    @Test
    public void valorDeducoesTest() {
        // TODO: test valorDeducoes
    }

    /**
     * Test the property 'valorPis'
     */
    @Test
    public void valorPisTest() {
        // TODO: test valorPis
    }

    /**
     * Test the property 'valorCofins'
     */
    @Test
    public void valorCofinsTest() {
        // TODO: test valorCofins
    }

    /**
     * Test the property 'valorInss'
     */
    @Test
    public void valorInssTest() {
        // TODO: test valorInss
    }

    /**
     * Test the property 'valorIr'
     */
    @Test
    public void valorIrTest() {
        // TODO: test valorIr
    }

    /**
     * Test the property 'valorCsll'
     */
    @Test
    public void valorCsllTest() {
        // TODO: test valorCsll
    }

    /**
     * Test the property 'valorOutrasRetencoes'
     */
    @Test
    public void valorOutrasRetencoesTest() {
        // TODO: test valorOutrasRetencoes
    }

    /**
     * Test the property 'valorIss'
     */
    @Test
    public void valorIssTest() {
        // TODO: test valorIss
    }

    /**
     * Test the property 'valorIssRetido'
     */
    @Test
    public void valorIssRetidoTest() {
        // TODO: test valorIssRetido
    }

    /**
     * Test the property 'valorLiquido'
     */
    @Test
    public void valorLiquidoTest() {
        // TODO: test valorLiquido
    }

    /**
     * Test the property 'aliquotaIss'
     */
    @Test
    public void aliquotaIssTest() {
        // TODO: test aliquotaIss
    }

    /**
     * Test the property 'aliquotaPis'
     */
    @Test
    public void aliquotaPisTest() {
        // TODO: test aliquotaPis
    }

    /**
     * Test the property 'aliquotaCofins'
     */
    @Test
    public void aliquotaCofinsTest() {
        // TODO: test aliquotaCofins
    }

    /**
     * Test the property 'aliquotaInss'
     */
    @Test
    public void aliquotaInssTest() {
        // TODO: test aliquotaInss
    }

    /**
     * Test the property 'aliquotaIr'
     */
    @Test
    public void aliquotaIrTest() {
        // TODO: test aliquotaIr
    }

    /**
     * Test the property 'aliquotaCsll'
     */
    @Test
    public void aliquotaCsllTest() {
        // TODO: test aliquotaCsll
    }

    /**
     * Test the property 'descontoIncondicionado'
     */
    @Test
    public void descontoIncondicionadoTest() {
        // TODO: test descontoIncondicionado
    }

    /**
     * Test the property 'descontoCondicionado'
     */
    @Test
    public void descontoCondicionadoTest() {
        // TODO: test descontoCondicionado
    }

}
