/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.com.caonulisses.nuvemfiscalsdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import io.github.com.caonulisses.nuvemfiscalsdk.model.BeneficioMunicipal;
import io.github.com.caonulisses.nuvemfiscalsdk.model.ExigSuspensa;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TribMunicipal
 */
public class TribMunicipalTest {
    private final TribMunicipal model = new TribMunicipal();

    /**
     * Model tests for TribMunicipal
     */
    @Test
    public void testTribMunicipal() {
        // TODO: test TribMunicipal
    }

    /**
     * Test the property 'tribISSQN'
     */
    @Test
    public void tribISSQNTest() {
        // TODO: test tribISSQN
    }

    /**
     * Test the property 'cLocIncid'
     */
    @Test
    public void cLocIncidTest() {
        // TODO: test cLocIncid
    }

    /**
     * Test the property 'cPaisResult'
     */
    @Test
    public void cPaisResultTest() {
        // TODO: test cPaisResult
    }

    /**
     * Test the property 'BM'
     */
    @Test
    public void BMTest() {
        // TODO: test BM
    }

    /**
     * Test the property 'exigSusp'
     */
    @Test
    public void exigSuspTest() {
        // TODO: test exigSusp
    }

    /**
     * Test the property 'tpImunidade'
     */
    @Test
    public void tpImunidadeTest() {
        // TODO: test tpImunidade
    }

    /**
     * Test the property 'vBC'
     */
    @Test
    public void vBCTest() {
        // TODO: test vBC
    }

    /**
     * Test the property 'pAliq'
     */
    @Test
    public void pAliqTest() {
        // TODO: test pAliq
    }

    /**
     * Test the property 'vISSQN'
     */
    @Test
    public void vISSQNTest() {
        // TODO: test vISSQN
    }

    /**
     * Test the property 'tpRetISSQN'
     */
    @Test
    public void tpRetISSQNTest() {
        // TODO: test tpRetISSQN
    }

    /**
     * Test the property 'vLiq'
     */
    @Test
    public void vLiqTest() {
        // TODO: test vLiq
    }

}
