/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ContaCota
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class ContaCota {
  public static final String SERIALIZED_NAME_NOME = "nome";
  @SerializedName(SERIALIZED_NAME_NOME)
  @javax.annotation.Nullable
  private String nome;

  public static final String SERIALIZED_NAME_CONSUMO = "consumo";
  @SerializedName(SERIALIZED_NAME_CONSUMO)
  @javax.annotation.Nullable
  private Integer consumo;

  public static final String SERIALIZED_NAME_LIMITE = "limite";
  @SerializedName(SERIALIZED_NAME_LIMITE)
  @javax.annotation.Nullable
  private Integer limite;

  public ContaCota() {
  }

  public ContaCota nome(@javax.annotation.Nullable String nome) {
    this.nome = nome;
    return this;
  }

  /**
   * Get nome
   * @return nome
   */
  @javax.annotation.Nullable
  public String getNome() {
    return nome;
  }

  public void setNome(@javax.annotation.Nullable String nome) {
    this.nome = nome;
  }


  public ContaCota consumo(@javax.annotation.Nullable Integer consumo) {
    this.consumo = consumo;
    return this;
  }

  /**
   * Get consumo
   * @return consumo
   */
  @javax.annotation.Nullable
  public Integer getConsumo() {
    return consumo;
  }

  public void setConsumo(@javax.annotation.Nullable Integer consumo) {
    this.consumo = consumo;
  }


  public ContaCota limite(@javax.annotation.Nullable Integer limite) {
    this.limite = limite;
    return this;
  }

  /**
   * Get limite
   * @return limite
   */
  @javax.annotation.Nullable
  public Integer getLimite() {
    return limite;
  }

  public void setLimite(@javax.annotation.Nullable Integer limite) {
    this.limite = limite;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContaCota contaCota = (ContaCota) o;
    return Objects.equals(this.nome, contaCota.nome) &&
        Objects.equals(this.consumo, contaCota.consumo) &&
        Objects.equals(this.limite, contaCota.limite);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nome, consumo, limite);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContaCota {\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    consumo: ").append(toIndentedString(consumo)).append("\n");
    sb.append("    limite: ").append(toIndentedString(limite)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("nome");
    openapiFields.add("consumo");
    openapiFields.add("limite");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ContaCota
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContaCota.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContaCota is not found in the empty JSON string", ContaCota.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContaCota.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContaCota` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nome") != null && !jsonObj.get("nome").isJsonNull()) && !jsonObj.get("nome").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nome` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nome").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContaCota.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContaCota' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContaCota> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContaCota.class));

       return (TypeAdapter<T>) new TypeAdapter<ContaCota>() {
           @Override
           public void write(JsonWriter out, ContaCota value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContaCota read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ContaCota given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ContaCota
   * @throws IOException if the JSON string is invalid with respect to ContaCota
   */
  public static ContaCota fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContaCota.class);
  }

  /**
   * Convert an instance of ContaCota to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

