/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Dados do PIS Substituição Tributária.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class NfeSefazPISST {
  public static final String SERIALIZED_NAME_V_B_C = "vBC";
  @SerializedName(SERIALIZED_NAME_V_B_C)
  @javax.annotation.Nullable
  private BigDecimal vBC;

  public static final String SERIALIZED_NAME_P_P_I_S = "pPIS";
  @SerializedName(SERIALIZED_NAME_P_P_I_S)
  @javax.annotation.Nullable
  private BigDecimal pPIS;

  public static final String SERIALIZED_NAME_Q_B_C_PROD = "qBCProd";
  @SerializedName(SERIALIZED_NAME_Q_B_C_PROD)
  @javax.annotation.Nullable
  private BigDecimal qBCProd;

  public static final String SERIALIZED_NAME_V_ALIQ_PROD = "vAliqProd";
  @SerializedName(SERIALIZED_NAME_V_ALIQ_PROD)
  @javax.annotation.Nullable
  private BigDecimal vAliqProd;

  public static final String SERIALIZED_NAME_V_P_I_S = "vPIS";
  @SerializedName(SERIALIZED_NAME_V_P_I_S)
  @javax.annotation.Nullable
  private BigDecimal vPIS;

  public static final String SERIALIZED_NAME_IND_SOMA_P_I_S_S_T = "indSomaPISST";
  @SerializedName(SERIALIZED_NAME_IND_SOMA_P_I_S_S_T)
  @javax.annotation.Nullable
  private Integer indSomaPISST;

  public NfeSefazPISST() {
  }

  public NfeSefazPISST vBC(@javax.annotation.Nullable BigDecimal vBC) {
    this.vBC = vBC;
    return this;
  }

  /**
   * Valor da BC do PIS ST.
   * minimum: 0
   * @return vBC
   */
  @javax.annotation.Nullable
  public BigDecimal getvBC() {
    return vBC;
  }

  public void setvBC(@javax.annotation.Nullable BigDecimal vBC) {
    this.vBC = vBC;
  }


  public NfeSefazPISST pPIS(@javax.annotation.Nullable BigDecimal pPIS) {
    this.pPIS = pPIS;
    return this;
  }

  /**
   * Alíquota do PIS ST (em percentual).
   * minimum: 0
   * @return pPIS
   */
  @javax.annotation.Nullable
  public BigDecimal getpPIS() {
    return pPIS;
  }

  public void setpPIS(@javax.annotation.Nullable BigDecimal pPIS) {
    this.pPIS = pPIS;
  }


  public NfeSefazPISST qBCProd(@javax.annotation.Nullable BigDecimal qBCProd) {
    this.qBCProd = qBCProd;
    return this;
  }

  /**
   * Quantidade Vendida.
   * minimum: 0
   * @return qBCProd
   */
  @javax.annotation.Nullable
  public BigDecimal getqBCProd() {
    return qBCProd;
  }

  public void setqBCProd(@javax.annotation.Nullable BigDecimal qBCProd) {
    this.qBCProd = qBCProd;
  }


  public NfeSefazPISST vAliqProd(@javax.annotation.Nullable BigDecimal vAliqProd) {
    this.vAliqProd = vAliqProd;
    return this;
  }

  /**
   * Alíquota do PIS ST (em reais).
   * minimum: 0
   * @return vAliqProd
   */
  @javax.annotation.Nullable
  public BigDecimal getvAliqProd() {
    return vAliqProd;
  }

  public void setvAliqProd(@javax.annotation.Nullable BigDecimal vAliqProd) {
    this.vAliqProd = vAliqProd;
  }


  public NfeSefazPISST vPIS(@javax.annotation.Nullable BigDecimal vPIS) {
    this.vPIS = vPIS;
    return this;
  }

  /**
   * Valor do PIS ST.
   * minimum: 0
   * @return vPIS
   */
  @javax.annotation.Nullable
  public BigDecimal getvPIS() {
    return vPIS;
  }

  public void setvPIS(@javax.annotation.Nullable BigDecimal vPIS) {
    this.vPIS = vPIS;
  }


  public NfeSefazPISST indSomaPISST(@javax.annotation.Nullable Integer indSomaPISST) {
    this.indSomaPISST = indSomaPISST;
    return this;
  }

  /**
   * Indica se o valor do PISST compõe o valor total da NF-e.
   * @return indSomaPISST
   */
  @javax.annotation.Nullable
  public Integer getIndSomaPISST() {
    return indSomaPISST;
  }

  public void setIndSomaPISST(@javax.annotation.Nullable Integer indSomaPISST) {
    this.indSomaPISST = indSomaPISST;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NfeSefazPISST nfeSefazPISST = (NfeSefazPISST) o;
    return Objects.equals(this.vBC, nfeSefazPISST.vBC) &&
        Objects.equals(this.pPIS, nfeSefazPISST.pPIS) &&
        Objects.equals(this.qBCProd, nfeSefazPISST.qBCProd) &&
        Objects.equals(this.vAliqProd, nfeSefazPISST.vAliqProd) &&
        Objects.equals(this.vPIS, nfeSefazPISST.vPIS) &&
        Objects.equals(this.indSomaPISST, nfeSefazPISST.indSomaPISST);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(vBC, pPIS, qBCProd, vAliqProd, vPIS, indSomaPISST);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NfeSefazPISST {\n");
    sb.append("    vBC: ").append(toIndentedString(vBC)).append("\n");
    sb.append("    pPIS: ").append(toIndentedString(pPIS)).append("\n");
    sb.append("    qBCProd: ").append(toIndentedString(qBCProd)).append("\n");
    sb.append("    vAliqProd: ").append(toIndentedString(vAliqProd)).append("\n");
    sb.append("    vPIS: ").append(toIndentedString(vPIS)).append("\n");
    sb.append("    indSomaPISST: ").append(toIndentedString(indSomaPISST)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("vBC");
    openapiFields.add("pPIS");
    openapiFields.add("qBCProd");
    openapiFields.add("vAliqProd");
    openapiFields.add("vPIS");
    openapiFields.add("indSomaPISST");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("vPIS");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NfeSefazPISST
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NfeSefazPISST.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NfeSefazPISST is not found in the empty JSON string", NfeSefazPISST.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NfeSefazPISST.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NfeSefazPISST` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NfeSefazPISST.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NfeSefazPISST.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NfeSefazPISST' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NfeSefazPISST> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NfeSefazPISST.class));

       return (TypeAdapter<T>) new TypeAdapter<NfeSefazPISST>() {
           @Override
           public void write(JsonWriter out, NfeSefazPISST value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NfeSefazPISST read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NfeSefazPISST given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NfeSefazPISST
   * @throws IOException if the JSON string is invalid with respect to NfeSefazPISST
   */
  public static NfeSefazPISST fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NfeSefazPISST.class);
  }

  /**
   * Convert an instance of NfeSefazPISST to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

