/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.NfseMensagemRetorno;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * NfseCancelamento
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class NfseCancelamento {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDENTE("pendente"),
    
    FILA_CANCELAMENTO("fila_cancelamento"),
    
    CONCLUIDO("concluido"),
    
    REJEITADO("rejeitado"),
    
    ERRO("erro");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_CODIGO = "codigo";
  @SerializedName(SERIALIZED_NAME_CODIGO)
  @javax.annotation.Nullable
  private String codigo;

  public static final String SERIALIZED_NAME_MOTIVO = "motivo";
  @SerializedName(SERIALIZED_NAME_MOTIVO)
  @javax.annotation.Nullable
  private String motivo;

  public static final String SERIALIZED_NAME_DATA_HORA = "data_hora";
  @SerializedName(SERIALIZED_NAME_DATA_HORA)
  @javax.annotation.Nullable
  private OffsetDateTime dataHora;

  public static final String SERIALIZED_NAME_MENSAGENS = "mensagens";
  @SerializedName(SERIALIZED_NAME_MENSAGENS)
  @javax.annotation.Nullable
  private List<NfseMensagemRetorno> mensagens = new ArrayList<>();

  public NfseCancelamento() {
  }

  public NfseCancelamento id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * ID único do cancelamento gerado automaticamente pela Nuvem Fiscal.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public NfseCancelamento status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public NfseCancelamento codigo(@javax.annotation.Nullable String codigo) {
    this.codigo = codigo;
    return this;
  }

  /**
   * Get codigo
   * @return codigo
   */
  @javax.annotation.Nullable
  public String getCodigo() {
    return codigo;
  }

  public void setCodigo(@javax.annotation.Nullable String codigo) {
    this.codigo = codigo;
  }


  public NfseCancelamento motivo(@javax.annotation.Nullable String motivo) {
    this.motivo = motivo;
    return this;
  }

  /**
   * Get motivo
   * @return motivo
   */
  @javax.annotation.Nullable
  public String getMotivo() {
    return motivo;
  }

  public void setMotivo(@javax.annotation.Nullable String motivo) {
    this.motivo = motivo;
  }


  public NfseCancelamento dataHora(@javax.annotation.Nullable OffsetDateTime dataHora) {
    this.dataHora = dataHora;
    return this;
  }

  /**
   * Get dataHora
   * @return dataHora
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDataHora() {
    return dataHora;
  }

  public void setDataHora(@javax.annotation.Nullable OffsetDateTime dataHora) {
    this.dataHora = dataHora;
  }


  public NfseCancelamento mensagens(@javax.annotation.Nullable List<NfseMensagemRetorno> mensagens) {
    this.mensagens = mensagens;
    return this;
  }

  public NfseCancelamento addMensagensItem(NfseMensagemRetorno mensagensItem) {
    if (this.mensagens == null) {
      this.mensagens = new ArrayList<>();
    }
    this.mensagens.add(mensagensItem);
    return this;
  }

  /**
   * Get mensagens
   * @return mensagens
   */
  @javax.annotation.Nullable
  public List<NfseMensagemRetorno> getMensagens() {
    return mensagens;
  }

  public void setMensagens(@javax.annotation.Nullable List<NfseMensagemRetorno> mensagens) {
    this.mensagens = mensagens;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NfseCancelamento nfseCancelamento = (NfseCancelamento) o;
    return Objects.equals(this.id, nfseCancelamento.id) &&
        Objects.equals(this.status, nfseCancelamento.status) &&
        Objects.equals(this.codigo, nfseCancelamento.codigo) &&
        Objects.equals(this.motivo, nfseCancelamento.motivo) &&
        Objects.equals(this.dataHora, nfseCancelamento.dataHora) &&
        Objects.equals(this.mensagens, nfseCancelamento.mensagens);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, codigo, motivo, dataHora, mensagens);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NfseCancelamento {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    codigo: ").append(toIndentedString(codigo)).append("\n");
    sb.append("    motivo: ").append(toIndentedString(motivo)).append("\n");
    sb.append("    dataHora: ").append(toIndentedString(dataHora)).append("\n");
    sb.append("    mensagens: ").append(toIndentedString(mensagens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("status");
    openapiFields.add("codigo");
    openapiFields.add("motivo");
    openapiFields.add("data_hora");
    openapiFields.add("mensagens");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NfseCancelamento
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NfseCancelamento.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NfseCancelamento is not found in the empty JSON string", NfseCancelamento.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NfseCancelamento.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NfseCancelamento` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("codigo") != null && !jsonObj.get("codigo").isJsonNull()) && !jsonObj.get("codigo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codigo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codigo").toString()));
      }
      if ((jsonObj.get("motivo") != null && !jsonObj.get("motivo").isJsonNull()) && !jsonObj.get("motivo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `motivo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("motivo").toString()));
      }
      if (jsonObj.get("mensagens") != null && !jsonObj.get("mensagens").isJsonNull()) {
        JsonArray jsonArraymensagens = jsonObj.getAsJsonArray("mensagens");
        if (jsonArraymensagens != null) {
          // ensure the json data is an array
          if (!jsonObj.get("mensagens").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `mensagens` to be an array in the JSON string but got `%s`", jsonObj.get("mensagens").toString()));
          }

          // validate the optional field `mensagens` (array)
          for (int i = 0; i < jsonArraymensagens.size(); i++) {
            NfseMensagemRetorno.validateJsonElement(jsonArraymensagens.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NfseCancelamento.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NfseCancelamento' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NfseCancelamento> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NfseCancelamento.class));

       return (TypeAdapter<T>) new TypeAdapter<NfseCancelamento>() {
           @Override
           public void write(JsonWriter out, NfseCancelamento value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NfseCancelamento read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NfseCancelamento given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NfseCancelamento
   * @throws IOException if the JSON string is invalid with respect to NfseCancelamento
   */
  public static NfseCancelamento fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NfseCancelamento.class);
  }

  /**
   * Convert an instance of NfseCancelamento to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

