/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RpsDadosConstrucaoCivil
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class RpsDadosConstrucaoCivil {
  public static final String SERIALIZED_NAME_CODIGO_OBRA = "codigo_obra";
  @SerializedName(SERIALIZED_NAME_CODIGO_OBRA)
  @javax.annotation.Nullable
  private String codigoObra;

  public static final String SERIALIZED_NAME_ART = "art";
  @SerializedName(SERIALIZED_NAME_ART)
  @javax.annotation.Nullable
  private String art;

  public RpsDadosConstrucaoCivil() {
  }

  public RpsDadosConstrucaoCivil codigoObra(@javax.annotation.Nullable String codigoObra) {
    this.codigoObra = codigoObra;
    return this;
  }

  /**
   * Get codigoObra
   * @return codigoObra
   */
  @javax.annotation.Nullable
  public String getCodigoObra() {
    return codigoObra;
  }

  public void setCodigoObra(@javax.annotation.Nullable String codigoObra) {
    this.codigoObra = codigoObra;
  }


  public RpsDadosConstrucaoCivil art(@javax.annotation.Nullable String art) {
    this.art = art;
    return this;
  }

  /**
   * Get art
   * @return art
   */
  @javax.annotation.Nullable
  public String getArt() {
    return art;
  }

  public void setArt(@javax.annotation.Nullable String art) {
    this.art = art;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RpsDadosConstrucaoCivil rpsDadosConstrucaoCivil = (RpsDadosConstrucaoCivil) o;
    return Objects.equals(this.codigoObra, rpsDadosConstrucaoCivil.codigoObra) &&
        Objects.equals(this.art, rpsDadosConstrucaoCivil.art);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoObra, art);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RpsDadosConstrucaoCivil {\n");
    sb.append("    codigoObra: ").append(toIndentedString(codigoObra)).append("\n");
    sb.append("    art: ").append(toIndentedString(art)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("codigo_obra");
    openapiFields.add("art");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RpsDadosConstrucaoCivil
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RpsDadosConstrucaoCivil.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RpsDadosConstrucaoCivil is not found in the empty JSON string", RpsDadosConstrucaoCivil.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RpsDadosConstrucaoCivil.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RpsDadosConstrucaoCivil` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("codigo_obra") != null && !jsonObj.get("codigo_obra").isJsonNull()) && !jsonObj.get("codigo_obra").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codigo_obra` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codigo_obra").toString()));
      }
      if ((jsonObj.get("art") != null && !jsonObj.get("art").isJsonNull()) && !jsonObj.get("art").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `art` to be a primitive type in the JSON string but got `%s`", jsonObj.get("art").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RpsDadosConstrucaoCivil.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RpsDadosConstrucaoCivil' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RpsDadosConstrucaoCivil> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RpsDadosConstrucaoCivil.class));

       return (TypeAdapter<T>) new TypeAdapter<RpsDadosConstrucaoCivil>() {
           @Override
           public void write(JsonWriter out, RpsDadosConstrucaoCivil value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RpsDadosConstrucaoCivil read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RpsDadosConstrucaoCivil given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RpsDadosConstrucaoCivil
   * @throws IOException if the JSON string is invalid with respect to RpsDadosConstrucaoCivil
   */
  public static RpsDadosConstrucaoCivil fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RpsDadosConstrucaoCivil.class);
  }

  /**
   * Convert an instance of RpsDadosConstrucaoCivil to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

