/*
 * API Nuvem Fiscal
 * API para automação comercial e documentos fiscais.
 *
 * The version of the OpenAPI document: 2.44.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.RpsPedidoEmissao;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * RpsPedidoEmissaoLote
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-30T14:00:11.942973268-03:00[America/Sao_Paulo]", comments = "Generator version: 7.10.0")
public class RpsPedidoEmissaoLote {
  /**
   * Identificação do Ambiente.
   */
  @JsonAdapter(AmbienteEnum.Adapter.class)
  public enum AmbienteEnum {
    HOMOLOGACAO("homologacao"),
    
    PRODUCAO("producao");

    private String value;

    AmbienteEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AmbienteEnum fromValue(String value) {
      for (AmbienteEnum b : AmbienteEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AmbienteEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AmbienteEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AmbienteEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AmbienteEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AmbienteEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_AMBIENTE = "ambiente";
  @SerializedName(SERIALIZED_NAME_AMBIENTE)
  @javax.annotation.Nullable
  private AmbienteEnum ambiente;

  public static final String SERIALIZED_NAME_REFERENCIA = "referencia";
  @SerializedName(SERIALIZED_NAME_REFERENCIA)
  @javax.annotation.Nullable
  private String referencia;

  public static final String SERIALIZED_NAME_LISTA_RPS = "lista_rps";
  @SerializedName(SERIALIZED_NAME_LISTA_RPS)
  @javax.annotation.Nullable
  private List<RpsPedidoEmissao> listaRps = new ArrayList<>();

  public RpsPedidoEmissaoLote() {
  }

  public RpsPedidoEmissaoLote ambiente(@javax.annotation.Nullable AmbienteEnum ambiente) {
    this.ambiente = ambiente;
    return this;
  }

  /**
   * Identificação do Ambiente.
   * @return ambiente
   */
  @javax.annotation.Nullable
  public AmbienteEnum getAmbiente() {
    return ambiente;
  }

  public void setAmbiente(@javax.annotation.Nullable AmbienteEnum ambiente) {
    this.ambiente = ambiente;
  }


  public RpsPedidoEmissaoLote referencia(@javax.annotation.Nullable String referencia) {
    this.referencia = referencia;
    return this;
  }

  /**
   * Seu identificador único para este documento. Opcional, ajuda a evitar o envio duplicado de um mesmo documento.
   * @return referencia
   */
  @javax.annotation.Nullable
  public String getReferencia() {
    return referencia;
  }

  public void setReferencia(@javax.annotation.Nullable String referencia) {
    this.referencia = referencia;
  }


  public RpsPedidoEmissaoLote listaRps(@javax.annotation.Nullable List<RpsPedidoEmissao> listaRps) {
    this.listaRps = listaRps;
    return this;
  }

  public RpsPedidoEmissaoLote addListaRpsItem(RpsPedidoEmissao listaRpsItem) {
    if (this.listaRps == null) {
      this.listaRps = new ArrayList<>();
    }
    this.listaRps.add(listaRpsItem);
    return this;
  }

  /**
   * Get listaRps
   * @return listaRps
   */
  @javax.annotation.Nullable
  public List<RpsPedidoEmissao> getListaRps() {
    return listaRps;
  }

  public void setListaRps(@javax.annotation.Nullable List<RpsPedidoEmissao> listaRps) {
    this.listaRps = listaRps;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RpsPedidoEmissaoLote rpsPedidoEmissaoLote = (RpsPedidoEmissaoLote) o;
    return Objects.equals(this.ambiente, rpsPedidoEmissaoLote.ambiente) &&
        Objects.equals(this.referencia, rpsPedidoEmissaoLote.referencia) &&
        Objects.equals(this.listaRps, rpsPedidoEmissaoLote.listaRps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ambiente, referencia, listaRps);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RpsPedidoEmissaoLote {\n");
    sb.append("    ambiente: ").append(toIndentedString(ambiente)).append("\n");
    sb.append("    referencia: ").append(toIndentedString(referencia)).append("\n");
    sb.append("    listaRps: ").append(toIndentedString(listaRps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ambiente");
    openapiFields.add("referencia");
    openapiFields.add("lista_rps");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ambiente");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RpsPedidoEmissaoLote
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RpsPedidoEmissaoLote.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RpsPedidoEmissaoLote is not found in the empty JSON string", RpsPedidoEmissaoLote.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RpsPedidoEmissaoLote.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RpsPedidoEmissaoLote` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RpsPedidoEmissaoLote.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("ambiente") != null && !jsonObj.get("ambiente").isJsonNull()) && !jsonObj.get("ambiente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ambiente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ambiente").toString()));
      }
      // validate the required field `ambiente`
      AmbienteEnum.validateJsonElement(jsonObj.get("ambiente"));
      if ((jsonObj.get("referencia") != null && !jsonObj.get("referencia").isJsonNull()) && !jsonObj.get("referencia").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referencia` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referencia").toString()));
      }
      if (jsonObj.get("lista_rps") != null && !jsonObj.get("lista_rps").isJsonNull()) {
        JsonArray jsonArraylistaRps = jsonObj.getAsJsonArray("lista_rps");
        if (jsonArraylistaRps != null) {
          // ensure the json data is an array
          if (!jsonObj.get("lista_rps").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `lista_rps` to be an array in the JSON string but got `%s`", jsonObj.get("lista_rps").toString()));
          }

          // validate the optional field `lista_rps` (array)
          for (int i = 0; i < jsonArraylistaRps.size(); i++) {
            RpsPedidoEmissao.validateJsonElement(jsonArraylistaRps.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RpsPedidoEmissaoLote.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RpsPedidoEmissaoLote' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RpsPedidoEmissaoLote> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RpsPedidoEmissaoLote.class));

       return (TypeAdapter<T>) new TypeAdapter<RpsPedidoEmissaoLote>() {
           @Override
           public void write(JsonWriter out, RpsPedidoEmissaoLote value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RpsPedidoEmissaoLote read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RpsPedidoEmissaoLote given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RpsPedidoEmissaoLote
   * @throws IOException if the JSON string is invalid with respect to RpsPedidoEmissaoLote
   */
  public static RpsPedidoEmissaoLote fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RpsPedidoEmissaoLote.class);
  }

  /**
   * Convert an instance of RpsPedidoEmissaoLote to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

